name: "policy"
ask_order: ["access_control", "data_masking", "quality_gates", "retention_policy", "evaluation_points"]
prompts:
  access_control: "What access control rules? Example: allow analysts and engineers, deny external users, role-based access"
  data_masking: "What data masking rules? Example: mask email and phone numbers, hash sensitive data, anonymize user ids"
  quality_gates: "What quality gates? Example: customer_id not null, email unique, age between 0-120, valid email format"
  retention_policy: "What retention policy? Example: delete after 365 days, archive after 7 years, keep forever"
  evaluation_points: "When to evaluate policies? Example: design time, CI/CD pipeline, runtime, data ingestion"
completion_message: "Policy configuration captured. Data governance policies will be applied to the data product."
policy_patterns:
  - "allow/deny roles: role1, role2, role3"
  - "mask columns: column1, column2 for role1, role2"
  - "quality gates: column1 not null, column2 unique, column3 pattern"
  - "retention: delete after X days, archive after Y years"
keywords:
  - "policy"
  - "policies"
  - "access"
  - "masking"
  - "quality"
  - "retention"
