name: "provisioning"
ask_order: ["environment", "infrastructure", "deployment_type", "resources", "monitoring"]
prompts:
  environment: "Which environment? Example: dev, staging, prod, test, sandbox"
  infrastructure: "What infrastructure type? Example: kubernetes, lambda, ec2, gcp-compute, azure-vm, docker"
  deployment_type: "Deployment type? Example: blue-green, rolling, canary, recreate, rolling-update"
  resources: "What resources needed? Example: cpu: 2 cores, memory: 4GB, storage: 100GB, gpu: 1"
  monitoring: "Enable monitoring and alerting? Example: yes, no, or specify: prometheus, cloudwatch, datadog, grafana"
completion_message: "Provisioning configuration captured. Infrastructure will be deployed to the specified environment."
keywords:
  - "deploy"
  - "provision"
  - "infrastructure"
  - "environment"
