name: "schema_contract"
ask_order: ["output_name", "output_type", "sink_location", "freshness", "fields"]
prompts:
  output_name: "What is the output name? Example: customer_data, sales_summary, user_events, product_catalog"
  output_type: "What is the output type? Example: table, stream, api, file, view"
  sink_location: "Where to sink the data? Example: catalog.schema.table, s3://bucket/path, kafka://topic, api://endpoint"
  freshness: "What is the data freshness requirement? Example: 15m, 1h, daily, real-time, weekly"
  fields: "What fields to include? Example: customer_id string pk, email string pii, name string, age integer, created_at timestamp"
completion_message: "Schema contract captured. Data product schema and SLA requirements are defined."
field_patterns:
  - "field_name data_type [pk] [pii] [description]"
  - "Examples: customer_id string pk, email string pii, name string, age integer, created_at timestamp"
  - "Data types: string, integer, float, boolean, date, timestamp, decimal, array, struct"
  - "Flags: pk (primary key), pii (personal data), required (not null)"
keywords:
  - "schema"
  - "contract"
  - "fields"
  - "output"
  - "table"
